name: Bug Report
description: Report a reproducible bug
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      render: shell

  - type: input
    id: version
    attributes:
      label: skillpm version / commit
      placeholder: e.g. main@abc123

  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: macOS/Linux + Go version
